# # # # # # # # # INSTALACIÓN DE CONTAINER BASE DE ROS2 # # # # # # # # # # # #

#Tomamos de imagen base la imagen de ROS2 Jazzy Jalisco
FROM ros:jazzy-ros-base-noble

ENV ROS_DISTRO=jazzy

SHELL ["/bin/bash", "-c"]



# # # # # # # # # # # INSTALACIÓN DE ESP-IDF # # # # # # # # # # # # # #

# Instalación de herramientas esenciales para la instalación de los framworks
RUN apt-get update -y && apt-get install --no-install-recommends -y \
    git \
    wget \
    flex \
    bison \
    gperf \
    python3 \
    python3-pip \
    python3-venv \
    cmake \
    ninja-build \
    ccache \
    libffi-dev \
    libssl-dev \
    dfu-util \
    libusb-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Instalación de IDF
WORKDIR /opt/esp
RUN git clone -b release/v5.2 --single-branch --recursive https://github.com/espressif/esp-idf.git idf
WORKDIR /opt/esp/idf
RUN /opt/esp/idf/install.sh esp32,esp32s3

# Script para la instalación de algunos paquetes para trabajar con el componente de Microros de IDF:
COPY ./setup_scripts/install_microros_idf_component_pip_packages.bash /root/.setup_scripts/install_microros_idf_component_pip_packages.bash



# # # # # # # # # # #   INSTALACIÓN DEL ROS2 DRIVER DE UNIVERSAL ROBOTS   # # # # # # # # # # # # # #

# TODO: Pasar a script para command post-build
COPY ./setup_scripts/install_ros_ur_driver.bash /root/.setup_scripts/install_ros_ur_driver.bash



# # # # # # # # # # # INSTALACIÓN DEl PAQUETE DE MICROROS # # # # # # # # # # # # # #

# TODO: Pasar a script para command post-build
COPY ./setup_scripts/install_microros_agent_ws.bash /root/.setup_scripts/install_microros_agent_ws.bash



# # # # # # # # # # # PERSONALIZACIÓN DE ENTORNO # # # # # # # # # # # # # #

# Instalación de herramientas para gustos personales
RUN apt-get update -y && apt-get install --no-install-recommends -y \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

# Copiamos el script de configuración (alias, etc.)
COPY ./setup_scripts/.bash_aliases /root/.bash_aliases

RUN dos2unix /root/.bash_aliases
RUN dos2unix /root/.setup_scripts/install_microros_idf_component_pip_packages.bash
RUN dos2unix /root/.setup_scripts/install_ros_ur_driver.bash
RUN dos2unix /root/.setup_scripts/install_microros_agent_ws.bash

WORKDIR /root